### PR TITLE
Add couple of missing minus signs.

### PR DESCRIPTION
**Pull request by lahvak**
I think that the signs in the equations and the signs in the solution are out of sync.

### CODE REVIEW

**Comment by jirilebl** [comment]
Thanks, I think a similar issue must appear in the corresponding problem on OPL because this is one of the problems that was taken from there (though they were all modified to some degree)

**Comment by lahvak** [comment]
Jo, zkusím to najít a opravit to taky tam.

--
Jan Hlavacek
Department of Mathematical Sciences, SVSU
(989) 964-2004 - https://space.lahvak.space/
________________________________

**Comment by jirilebl** [comment]
Bohuzel jsem byl blbej a nezapsal jsem jmena souboru.

**Comment by jirilebl** [comment]
Koukam se zkrz history a je to v OPL v poho.  Tu chybu jsem udelal ja tady kdyz jsem to menil na MathObjects.

**Comment by lahvak** [comment]
Jo, dobrý.

--
Jan Hlavacek
Department of Mathematical Sciences, SVSU
(989) 964-2004 - https://space.lahvak.space/
________________________________

**Pull request merged**
